#theme: jekyll-theme-leap-day
remote_theme: pmarsceill/just-the-docs

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "View on GitHub":
    - "https://github.com/ololx/cranberry"
  "Home":
    - "https://github.com/ololx.githib.io"  
    
# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true
